### ISSUE TITLE
Getting error on Docker startup

### ISSUE THREAD

**Issue by nigels0** [weltenwort/frigate-synology-dsm7#117]
Hi,

I'm trying to run Frigate on a RS422+ using this. I've set up the coral TPU in the serial port and think its being recognised:
` lsusb
|__usb1          1d6b:0002:0404 09  2.00  480MBit/s 0mA 1IF  (Linux 4.4.302+ xhci-hcd xHCI Host Controller 0000:05:00.3) hub
  |__1-1         f400:f400:0100 00  2.00  480MBit/s 200mA 1IF  (Synology DiskStation 7F00238D1C1A2E27)
|__usb2          1d6b:0003:0404 09  3.00 5000MBit/s 0mA 1IF  (Linux 4.4.302+ xhci-hcd xHCI Host Controller 0000:05:00.3) hub
  |__2-2         1a6e:089a:0100 00  3.10 5000MBit/s 896mA 1IF  ( ffffffd1ffffffb2ffffffdbffffffad)`

I'm using the docker-compose file exactly as shown and set up the config file as:
mqtt:
  enabled: False

cameras:
  Front_Door:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_CAMERA_1_RTSP_CREDENTIALS}@192.168.40.11:554/rtsp
          roles:
            - detect
The indentation is fine - it just isn't showing here.

I'm getting an error on startup though
`
date | stream | content
-- | -- | --
2024/02/08 14:19:56 | stdout | [s6-finish] sending all processes the KILL signal and exiting.
2024/02/08 14:19:53 | stdout | [s6-finish] sending all processes the TERM signal.
2024/02/08 14:19:53 | stdout | [s6-finish] waiting for services.
2024/02/08 14:19:53 | stdout | [cont-finish.d] done.
2024/02/08 14:19:53 | stdout | [cont-finish.d] executing container finish scripts...
2024/02/08 14:19:53 | stdout | [cmd] python3 exited 1
2024/02/08 14:19:52 | stdout | *************************************************************
2024/02/08 14:19:52 | stdout | ***    End Config Validation Errors                       ***
2024/02/08 14:19:52 | stdout | *************************************************************
2024/02/08 14:19:52 | stdout |  
2024/02/08 14:19:52 | stdout | extra fields not permitted (type=value_error.extra)
2024/02/08 14:19:52 | stdout | cameras -> Front_Door -> enabled
2024/02/08 14:19:52 | stdout | extra fields not permitted (type=value_error.extra)
2024/02/08 14:19:52 | stdout | mqtt -> enabled
2024/02/08 14:19:52 | stdout | field required (type=value_error.missing)
2024/02/08 14:19:52 | stdout | mqtt -> host
2024/02/08 14:19:52 | stdout | pydantic.error_wrappers.ValidationError: 3 validation errors for FrigateConfig
2024/02/08 14:19:52 | stdout | File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2024/02/08 14:19:52 | stdout | File "pydantic/main.py", line 521, in pydantic.main.BaseModel.parse_obj
2024/02/08 14:19:52 | stdout | return cls.parse_obj(config)
2024/02/08 14:19:52 | stdout | File "/opt/frigate/frigate/config.py", line 942, in parse_file
2024/02/08 14:19:52 | stdout | user_config = FrigateConfig.parse_file(config_file)
2024/02/08 14:19:52 | stdout | File "/opt/frigate/frigate/app.py", line 82, in init_config
2024/02/08 14:19:52 | stdout | self.init_config()
2024/02/08 14:19:52 | stdout | File "/opt/frigate/frigate/app.py", line 332, in start
2024/02/08 14:19:52 | stdout | Traceback (most recent call last):
2024/02/08 14:19:52 | stdout | extra fields not permitted (type=value_error.extra)
2024/02/08 14:19:52 | stdout | cameras -> Front_Door -> enabled
2024/02/08 14:19:52 | stdout | extra fields not permitted (type=value_error.extra)
2024/02/08 14:19:52 | stdout | mqtt -> enabled
2024/02/08 14:19:52 | stdout | field required (type=value_error.missing)
2024/02/08 14:19:52 | stdout | mqtt -> host
2024/02/08 14:19:52 | stdout | 3 validation errors for FrigateConfig
2024/02/08 14:19:52 | stdout | *************************************************************
2024/02/08 14:19:52 | stdout | ***    Config Validation Errors                           ***
2024/02/08 14:19:52 | stdout | *************************************************************
2024/02/08 14:19:52 | stdout | *************************************************************
2024/02/08 14:19:52 | stdout | ***    https://docs.frigate.video/configuration/index     ***
2024/02/08 14:19:52 | stdout | ***    Please check the docs at                           ***
2024/02/08 14:19:52 | stdout | ***    Your config file is not valid!                     ***
2024/02/08 14:19:52 | stdout | *************************************************************
2024/02/08 14:19:52 | stdout | *************************************************************

`

but I really can't see any errors in the config file!

**Comment by danuals** [comment]
what dsm version?  be handy to see cofig on correct format

**Comment by nigels0** [comment]
Its DSM 7.2.1-69057 Update 3 - trust me, the indentation is OK, but just can't seem to paste it here.

mqtt:
  host: 127.0.0.1
  user: "{FRIGATE_MQTT_USERNAME}"
  password: "{FRIGATE_MQTT_PASSWORD}"

cameras:
  Front_Door:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_CAMERA_1_RTSP_CREDENTIALS}@192.168.40.2:554/rtsp
          roles:
            - detect


I've set up a Mosquito MQTT server now on the same RS422+ (so the config has changed)

**Comment by danuals** [comment]
This is no longer needed. As of frigate 12 you can use the official release.

**Comment by danuals** [comment]
Start off by reinstalling using official frigate release. If using 13 changes have been made to the docker install Side of things. For this reason it’s best to start there fresh.

**Comment by nigels0** [comment]
Thanks - that seemed to fix it

**Comment by nigels0** [comment]
Use main image
