### ISSUE TITLE
Update frigate version

### ISSUE THREAD

**Issue by fufurax** [weltenwort/frigate-synology-dsm7#118]
Hi,

thanks for your work.

Is there a way to have the latest frigate version compatible with HA ?

```
Enregistreur: custom_components.frigate
Source: custom_components/frigate/__init__.py:201
intégration: Frigate ([documentation](https://github.com/blakeblackshear/frigate), [problèmes](https://github.com/blakeblackshear/frigate-hass-integration/issues))
S'est produit pour la première fois: 07:31:28 (4 occurrences)
Dernier enregistrement: 07:33:19

Using a Frigate server (http://192.168.1.30:6545/) with version 0.11.1-2eada21 <= 0.12.1 which is not compatible -- you must upgrade: https://github.com/blakeblackshear/frigate/releases
Using a Frigate server (http://192.168.1.30:6545) with version 0.11.1-2eada21 <= 0.12.1 which is not compatible -- you must upgrade: https://github.com/blakeblackshear/frigate/releases
```
Thanks

**Comment by danuals** [comment]
Yes, just use the official frigate version. This dsm branch is no longer needed. 
official frigate is now compatible with dsm 7

**Comment by fufurax** [comment]
> Yes, just use the official frigate version. This dsm branch is no longer needed. official frigate is now compatible with dsm 7

Strange. I can't access to Coral USB key with the official version :(

And it works like a charm with this one

**Comment by danuals** [comment]
What’s your docker compose  and configuration,
Edit: is the install ha add on or docker?

**Comment by fufurax** [comment]
issue fixed :/ missing container admin grant in DSM
