### ISSUE TITLE
Do you also need to install the edge TPU runtime

### ISSUE THREAD

**Issue by Chen2022** [weltenwort/frigate-synology-dsm7#52]
First of all, thank you very much. Your tool is great. Install your frigate-syntax-dsm7, and then Google core USB just needs to plug into synology to work normally? Don't I need to install the edge TPU runtime on the official website?

**Comment by weltenwort** [comment]
Hi @Chen2022, the runtime is contained inside of the frigate container, so no additional drivers should be required. That's also the reason why we have to expose the whole usb device tree to the container.

**Comment by Chen2022** [comment]
I see. Thank you
