### ISSUE TITLE
Language translation

### ISSUE THREAD

**Issue by siri10086** [weltenwort/frigate-synology-dsm7#64]
### Discussed in https://github.com/weltenwort/frigate-synology-dsm7/discussions/63

<div type='discussions-op-text'>

<sup>Originally posted by **siri10086** August 26, 2022</sup>
Is there any way to change these Title languages into other languages? I will translate and replace them myself
<img width="1414" alt="WX20220826-210520@2x" src="https://user-images.githubusercontent.com/61342291/186910298-6887dfc0-3f2b-4b26-95d0-6fec034d6508.png">
</div>

**Comment by weltenwort** [comment]
Hi @siri10086,

this repository is only providing customized docker images for running frigate on certain Synology NAS systems. Your request, while reasonable, would be best directed at https://github.com/blakeblackshear/frigate directly.
