### ISSUE TITLE
Some beginner help, please

### ISSUE THREAD

**Issue by ripvega** [weltenwort/frigate-synology-dsm7#89]
I've been running Frigate as a Home assistant addon for some time and it is excellent. Unfortunately, the CPU overhead is an issue so thought I'd look to run it elsewhere and came across your work.

I'm a complete docker novice though!

I have a Synology NAS but don't know if it has GIT. How do I find out?

I made the assumption that it doesn't and carried out step 2 and got this:
<img width="957" alt="Screenshot 2022-10-26 at 19 54 20" src="https://user-images.githubusercontent.com/42817627/198112237-b2d5cc98-fedf-42e1-acf5-47087d537daa.png">
So I assume that worked but I can't find the docker-compose.yml file on the NAS.

Where should it be?

Step 3 says to create the secrets.env file. Where on the NAS should it be it be saved?
Do I need a `FRIGATE_CAMERA_2_RTSP_CREDENTIALS=my-camera-2-username:my-camera-2-password` for each camera that I have?

I already have an extensive config file from running Frigate as a Home Assistant addon. Will this work in docker too?
What will I need to change as per step 5.

Many thanks for any help.

Ash

**Comment by weltenwort** [comment]
> Where should it be?

It should be in the working directory that you ran the `wget` command in.

> Step 3 says to create the secrets.env file. Where on the NAS should it be it be saved?

It's referred to in https://github.com/weltenwort/frigate-synology-dsm7/blob/bebb1c386acf29cdd7d1ec1d82bb44ae8a2a762c/docker-compose.yml#L22-L23, which means it should be put into the same directory as the compose file. Alternatively you can adjust the path in the compose file to point to a different location for that file.

> I already have an extensive config file from running Frigate as a Home Assistant addon. Will this work in docker too?

The file should work, because nothing about frigate itself changed. We just replaced the `libusb` library in the docker image. But if you didn't use a Coral accelerator in your previous installation you might want to change the detector configuration into something like the following:

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
```

Hope that helps?

**Comment by weltenwort** [comment]
> Do I need a `FRIGATE_CAMERA_2_RTSP_CREDENTIALS=my-camera-2-username:my-camera-2-password` for each camera that I have?

It's just one way to inject the passwords into the frigate configuration file. If each of your camera has different credentials (which would be good practice :wink:) then you'd have to inject the password for each. But you'd have to adapt your config file to read from the matching environment variable.

**Comment by ripvega** [comment]
Thank you.

I've got something running, albeit with a few issues, however, I'll work through them.

What should be the IP address for the Frigate web interface now, or where do I find it?

My Synology NAS is a t 10.0.1.235:5000, if that helps.

**Comment by ripvega** [comment]
I figured that out - 8001!

So nearly there and yet so far!

When opening the web interface all of the cameras are just green.

Any ideas?

**Comment by ripvega** [comment]
I'm starting to get this now - still with confusion.

I don't need any entries in the secrets file as my MQTT and camera passwords are all within my config file.

I can see recordings being saved and they play, but the web interface still shows green screens.

My container looks like this:
<img width="650" alt="Screenshot 2022-10-26 at 21 57 59" src="https://user-images.githubusercontent.com/42817627/198136370-620585a9-bd62-4166-82f9-afb8243d4f2e.png">
<img width="650" alt="Screenshot 2022-10-26 at 21 58 23" src="https://user-images.githubusercontent.com/42817627/198136456-93dbe200-fedb-451a-8d8b-4721c07edad0.png">
<img width="650" alt="Screenshot 2022-10-26 at 21 58 45" src="https://user-images.githubusercontent.com/42817627/198136527-62e9f8c2-4d13-407b-b22b-b382ba7fc589.png">
<img width="650" alt="Screenshot 2022-10-26 at 21 59 11" src="https://user-images.githubusercontent.com/42817627/198136610-15d1f210-2f40-43ef-ab1a-672407ad4ca0.png">

What could I be missing?

I really appreciate you taking the time to help.

**Comment by weltenwort** [comment]
> I figured that out - 8001!

Yes, sorry for not documenting that :see_no_evil: it's set here in the compose file:

https://github.com/weltenwort/frigate-synology-dsm7/blob/bebb1c386acf29cdd7d1ec1d82bb44ae8a2a762c/docker-compose.yml#L19-L21

> I can see recordings being saved and they play, but the web interface still shows green screens.

Then something with the rtmp streams is not correct. Can you share the docker container's log output so we can take a look if there's an error message in there? You can display it by running `docker-compose logs` in the directory with the compose file, via `docker container logs frigate_frigate_1` or in the container details in the synology docker UI.

**Comment by ripvega** [comment]
Progress!

I can now see the cameras in Home Assistant using the Frigate proxy addon and the integration is showing the camera entities and sensors.

So, it all seems good but what I'm not sure about is if my Coral TPU is being used.

Is there a way to check that?

**Comment by weltenwort** [comment]
Glad to hear you're making progress. `TPU found` should indicate that it has detected the Coral device. So if you don't have any additional CPU detectors configured it should be using the TPU. In my experience it stops running when no detectors were found.

**Comment by ripvega** [comment]
Thank you, that's very helpful.

I have a spare Coral TPU. Can it support two in docker?

Many, many thanks for your help. Moving my Frigate away from my Home
Assistant has made a huge difference and I appreciate your time.

**Comment by weltenwort** [comment]
> I have a spare Coral TPU. Can it support two in docker?

I haven't tried, but I don't see why not if you add them as detectors to your frigate config file.

> Thank you, that's very helpful.

Don't mention it :smile: I'll close this issue for now, but feel free to reopen or file a new one if you run into other problems.
