### ISSUE TITLE
Hw acceleration with m2 version of coral possible?

### ISSUE THREAD

**Issue by jmtatsch** [weltenwort/frigate-synology-dsm7#92]
Not really an issue but rather a question:
Do you think hardware acceleration would work with the m2 version of the coral
https://www.coral.ai/products/m2-accelerator-ae
and my DS920+ which has 2 m2 slots?

**Comment by weltenwort** [comment]
Hey @jmtatsch :wave: I don't have any first-hand experience with that, but I also don't want your question to go without a response. The only limitation of the M.2 slots that I have heard about is that any storage devices attached that way can't be included into the storage pool. But I don't have any positive confirmation of other types of M.2 devices being used either, sorry.

Have you considered asking this question in the [discussions section of the main frigate repo](https://github.com/blakeblackshear/frigate/discussions)? You might reach more people that way.

**Comment by jmtatsch** [comment]
Will do.
I have dug a bit deeper. There are some people who have asked about it but never tried it out.
Apparently one would need the pci-e driver in gasket-dkms and a bit different libedgetpu1-std for the m2 version.

Do you know if the pci-e driver has to be compiled/installed on the Synology directly or whether it's enough to install it in the docker?

**Comment by weltenwort** [comment]
Interesting question. If the container is given extensive privileges it should be possible to load kernel modules. The bigger problem might be that you'd probably need the specific kernel headers used by Synology. No idea if they can be found somewhere in the filesystem. :thinking: I'm only speculating once more, sorry.

**Comment by jmtatsch** [comment]
Good point. I think the risks and amount of work necessary outweigh the benefit. I ordered a yucky old usb stick then.
