### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by nmcrae85** [weltenwort/frigate-synology-dsm7#96]
Hi there. 

Just wanted to check this is not expected, right? It seems to be not having the permission to install?

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/32064932/211173152-846a0416-4c17-495c-ae2f-862d98412c55.png">

**Comment by nmcrae85** [comment]
Managed to solve this, with sudo -i

How do you perform step 3? Do you need to create new env? How do you do this via cli?

**Comment by nmcrae85** [comment]
I have managed to get this far now. I think it might be my lack of understanding of the env setting causing this error?

<img width="1334" alt="image" src="https://user-images.githubusercontent.com/32064932/211173521-3f55d47c-d44c-4e1f-b048-61f30dc08c83.png">

**Comment by nmcrae85** [comment]
@weltenwort - can you help? im not sure how to move from step 3 to 4. I dont have any files called config.yml in that directory as per the error. How do i create on the nas? what info needs to go into here

**Comment by baylanger** [comment]
@nmcrae85 Frigate 0.12 beta can run native on DSM.

This for me works but you need to adjust for your case.

```services:
  frigate:
    image: "ghcr.io/blakeblackshear/frigate:dev-581c259"
    container_name: "frigate"
    domainname: "yours.com"
    hostname: "frigate"
    privileged: true
    restart: "unless-stopped"
    shm_size: "128mb" # adjust
    devices:
      - "/dev/dri/renderD128" # for intel hwaccel
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
      - "/etc/localtime:/etc/localtime:ro"
      - "/volume1/docker/frigate/config/config.yml:/config/config.yml:ro"
      - "/volume1/docker/frigate/media:/media/frigate:rw"
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5050:5000" # web interface
#      - "1935:1935" # RTMP feeds
      - "8554:8554" # RTSP feeds
    environment:
      - LIBVA_DRIVER_NAME=i965
    env_file:
      - "./secrets.env"
      - ```

**Comment by nmcrae85** [comment]
@baylanger - do you download from the frigate website? Can you run from docker marketplace?

**Comment by jmtatsch** [comment]
ssh to your nas 
create the paths
copy or create the config files manually e.g. using the editor vi - if necessary use sudo before

**Comment by nmcrae85** [comment]
Sorry for the stupid questions. So to be clear (now I have the directories created). I need to create a file here - /volume1/docker/volumes/frigate-0-config/ called config.yml

The infomation in that file needs to be this?

  frigate:
    image: "ghcr.io/blakeblackshear/frigate:dev-581c259"
    container_name: "frigate"
    domainname: "yours.com"
    hostname: "frigate"
    privileged: true
    restart: "unless-stopped"
    shm_size: "128mb" # adjust
    devices:
      - "/dev/dri/renderD128" # for intel hwaccel
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
      - "/etc/localtime:/etc/localtime:ro"
      - "/volume1/docker/frigate/config/config.yml:/config/config.yml:ro"
      - "/volume1/docker/frigate/media:/media/frigate:rw"
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5050:5000" # web interface
#      - "1935:1935" # RTMP feeds
      - "8554:8554" # RTSP feeds
    environment:
      - LIBVA_DRIVER_NAME=i965
    env_file:
      - "./secrets.env"
      - ```

Im sure for you all this is basic, but im only just getting into docker/ containers and no background in dev @baylanger

**Comment by nmcrae85** [comment]
nmcrae@NAS-DS9:/$ cat <<EOF >secrets.env
> FRIGATE_MQTT_USERNAME=my-frigate-mqtt-username
> FRIGATE_MQTT_PASSWORD=my-frigate-mqtt-password
> FRIGATE_CAMERA_1_RTSP_CREDENTIALS=my-camera-1-username:my-camera-1-password
> FRIGATE_CAMERA_2_RTSP_CREDENTIALS=my-camera-2-username:my-camera-2-password
> EOF
-sh: secrets.env: Permission denied

This is the problem... everything else is in place. Im sure its just a noob error

**Comment by jmtatsch** [comment]
If you wanted to look at your secrets.env file the command would be 'cat secrets.env'.

**Comment by jmtatsch** [comment]
container_name: "frigate"
in config.yml
probably should not start with -

**Comment by nmcrae85** [comment]
There is no container name in config.yml just this exampe (with my config)

mqtt:
  host: mqtt.server.com
cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.0.10.10:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720

Inside the compose file I have the container name as just "frigate"

**Comment by nmcrae85** [comment]
fixed and working

**Comment by weltenwort** [comment]
Glad to hear you got it working, sorry for the lack of response. Thanks, everyone, for helping out!
